### ISSUE TITLE
JDK 11

### ISSUE THREAD

**Issue by DevOrc** [JonasHavers/javafeatures#1]
In your [post](https://medium.com/@jonashavers/how-to-use-java-10-with-travis-ci-363c7dc2f708) about testing JDK 10+ you stated that you cant run JDK 11 on Travis with gradle because the version installed there is outdated. However there is a work around that I found [here](https://stackoverflow.com/questions/52974252/problem-with-java-and-travis-ci-codacy-coverage-and-gradle). 

The following travis.yml will pass:

```yml
language: java
sudo: true
install: true

jdk:
- oraclejdk11
- oraclejdk8

before_install:
- chmod +x gradlew

script:
- ./gradlew -v
- ./gradlew clean test

```

**Note**: You need to update the gradle properties file to the following so that the gradle wrapper 
uses the most recent version
```properties
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

If you want, I can write a PR making the changes!
